# Generated by Django 2.2.5 on 2019-09-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
