# Generated by Django 2.2.5 on 2019-09-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.AddField(
            model_name='customer',
            name='cart',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
