# Generated by Django 2.2.5 on 2019-10-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20190930_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
