# Generated by Django 2.2.5 on 2019-10-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20191001_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='off_percent',
            new_name='percent',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='order_size',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='product_id',
        ),
        migrations.AddField(
            model_name='offer',
            name='free_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='include_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='include_category',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='include_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='percent_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='quantity_discount',
            field=models.BooleanField(default=False),
        ),
    ]
