# Generated by Django 2.2.5 on 2019-10-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20191003_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.ManyToManyField(default=None, to='shop.Category'),
        ),
    ]
