# Generated by Django 2.2.5 on 2019-10-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_offer_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='product',
            field=models.ManyToManyField(default=None, to='shop.Product'),
        ),
    ]
