# Generated by Django 2.2.5 on 2019-10-03 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20191003_2009'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='offer',
            index_together={('id', 'slug')},
        ),
    ]
