# Generated by Django 2.2.5 on 2019-10-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20191003_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
