# Generated by Django 2.2.5 on 2019-10-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20191003_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='shop.Category'),
        ),
    ]
