# Generated by Django 2.2.5 on 2019-10-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20191003_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='product',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='shop.Product'),
        ),
    ]
