# Generated by Django 2.2.5 on 2019-10-09 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_shop_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shop_details',
            new_name='Shop_detail',
        ),
    ]
