# Generated by Django 2.2.5 on 2019-10-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20191009_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_detail',
            name='cancellation_period',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='shop_detail',
            name='delivery_charge',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
