# Generated by Django 2.2.5 on 2019-10-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20191009_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_detail',
            name='shop_name',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
