# Generated by Django 2.2.5 on 2019-10-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_shop_detail_shop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_detail',
            name='shop_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
